### ISSUE TITLE
Indicators not saving and Results Framework not saving

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#1013]
### Current behavior
https://staging-activity.toladata.io/programs/dashboard
https://staging.toladata.io/admin/indicators/indicator/

Indicators and Results Framework are not saving to front-end or backend

### Expected behavior
Indicators should save. 

### Steps to reproduce the behavior

1. add an indicator
2. save/submit
3. indicator is not listed

**Comment by Menda** [comment]
Traceback found:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 90, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/code/api/views.py", line 287, in perform_create
    serializer.save(created_by=self.request.user)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 913, in create
    instance = ModelClass.objects.create(**validated_data)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/site-packages/indicators/models.py", line 378, in save
    super(Indicator, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1099, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "indicators_indicator_pkey"
```

Payload:

```
{
  "id": null,
  "name": "New Indicator",
  "number": "",
  "baseline": null,
  "lop_target": "20",
  "definition": "<p>Some definition</p>",
  "reporting_frequency": "",
  "key_performance_indicator": false,
  "unit_of_measure": "",
  "sector": "",
  "level": null,
  "objectives": [],
  "indicator_type": [],
  "method_of_analysis": "",
  "information_use": "",
  "approved_by": "",
  "approval_submitted_by": "",
  "responsible_person": "",
  "workflowlevel1": [
    "https://staging.toladata.io/api/workflowlevel1/17/"
  ],
  "localId": "2912de98-6840-8410-8a7d-a720f628a1e6"
}
```

**Comment by Menda** [comment]
Moved to https://github.com/toladata/ActivityAPI/issues/29

**Comment by karrla** [comment]
@Menda                       
 oops the add Result Framework is still causing a 500 error on submit

![image.png](https://images.zenhubusercontent.com/58b6f81951aa2c30577726c7/cbee5f61-70bb-4648-a9eb-68d762eb3c22)

**Comment by Menda** [comment]
Sorry. I was doing using a new DB admin and was only executing partially what I wanted. Try again @karrla
